services:
  go-app:
    image: mcr.microsoft.com/devcontainers/go:1-1.24-bookworm
    command: sleep infinity
    container_name: go-app
    volumes:
      - .:/workspace:cached
    ports:
      - "8080:8080"
    depends_on:
      - go-db

  go-db:
    image: postgres:17-alpine
    container_name: go-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go_db
    ports:
      - "5432:5432"
    volumes:
      - go-db-data:/var/lib/postgresql/data

volumes:
  go-db-data:
