services:
  gateway-app:
    image: mcr.microsoft.com/devcontainers/go:1-1.24-bookworm
    command: sleep infinity
    container_name: gateway-app
    volumes:
      - .:/workspace:cached
    ports:
      - "8080:8080"
    depends_on:
      - gateway-db

  gateway-db:
    image: postgres:17-alpine
    container_name: gateway-db
    environment:
      - POSTGRES_USER=gateway_user
      - POSTGRES_PASSWORD=gateway_pass
      - POSTGRES_DB=gateway_db
    ports:
      - "5432:5432"
    volumes:
      - gateway-db-data:/var/lib/postgresql/data

volumes:
  gateway-db-data:
