services:
  anti-fraud-app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    command: sleep infinity
    container_name: anti-fraud-app
    volumes:
      - .:/workspace:cached
    ports:
      - "3000:3000"
    depends_on:
      - anti-fraud-db

  anti-fraud-db:
    image: postgres:17-alpine
    container_name: anti-fraud-db
    environment:
      - POSTGRES_USER=anti_fraud_user
      - POSTGRES_PASSWORD=anti_fraud_pass
      - POSTGRES_DB=anti_fraud_db
    ports:
      - "5433:5432"
    volumes:
      - anti-fraud-db-data:/var/lib/postgresql/data

  gateway-app:
    image: mcr.microsoft.com/devcontainers/go:1-1.24-bookworm
    command: sleep infinity
    container_name: gateway-app
    volumes:
      - .:/workspace:cached
    ports:
      - "8080:8080"
    depends_on:
      - gateway-db

  gateway-db:
    image: postgres:17-alpine
    container_name: gateway-db
    environment:
      - POSTGRES_USER=gateway_user
      - POSTGRES_PASSWORD=gateway_pass
      - POSTGRES_DB=gateway_db
    ports:
      - "5432:5432"
    volumes:
      - gateway-db-data:/var/lib/postgresql/data

volumes:
  anti-fraud-db-data:
  gateway-db-data:
